@extends('layout.main')

@section('content')

<div class="container my-5">
    <h1>Home</h1>
    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum ullam nostrum voluptatem ratione adipisci incidunt rem, eos corrupti laborum dicta nemo animi voluptatum, nulla a! Veritatis, neque quod nesciunt sapiente vitae provident architecto quasi excepturi porro quo. Debitis numquam quas culpa excepturi, ratione assumenda ab officia ducimus et quaerat odit natus illo nihil molestiae dolore obcaecati sint a quod? Expedita vel iusto voluptas nulla excepturi quibusdam maiores similique, placeat praesentium molestias animi dolorum corporis ut temporibus voluptatibus, rerum quae ipsum assumenda eos consequuntur nihil optio ratione. Itaque pariatur ullam, quibusdam molestiae possimus nemo impedit aspernatur doloremque non ad fugiat atque vitae! Unde libero fugiat cupiditate quisquam, saepe corrupti at veniam hic itaque veritatis adipisci eaque dolorum porro sapiente numquam a animi corporis debitis quia facere. Nostrum veniam repellendus corporis, architecto natus nam facilis facere itaque tempore quo accusantium et excepturi eos esse dolorem nisi quos atque nulla quidem soluta expedita voluptates voluptatum, perspiciatis neque. Porro ab molestiae laborum, explicabo alias hic maxime ullam ipsam architecto quis sint culpa dicta ad fugit corporis excepturi quia, incidunt magnam vitae reiciendis veritatis neque. Ex dolorum illo autem dignissimos at eligendi consequuntur. Assumenda totam corrupti a modi perferendis eum doloremque minus, nostrum molestiae, magni maxime temporibus eveniet perspiciatis quos. Magni neque tempore omnis atque ducimus consequuntur quaerat tenetur possimus nesciunt sequi? Facilis quod quibusdam minus beatae non excepturi. Temporibus exercitationem eveniet, expedita ut sequi reiciendis, fuga deserunt sit vel nemo, sapiente tenetur porro fugiat voluptates suscipit nihil itaque hic iste ea. Corrupti, illo quia? Aut accusamus at doloribus alias sunt minima, dolores illo culpa provident dignissimos doloremque beatae obcaecati cupiditate quidem. Hic voluptatum laudantium consectetur eum quisquam quas qui quo vitae fugit voluptas distinctio autem nobis, ratione rerum enim saepe, dignissimos maiores quidem sequi aut voluptate? Sequi dicta quas nulla quam, similique rerum a!</p>
</div>

@endsection
